name: Build 5.10-BPF BakaSU Kernel

on:
  workflow_dispatch:
  schedule:
    - cron: '27 10 * * 4'
jobs:
  build:
    name: Compile Kernel
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Configure Fast APT Mirror
        uses: vegardit/fast-apt-mirror.sh@v1

      - name: Make Build Environment
        timeout-minutes: 10
        run: |
          sudo apt-get update
          sudo apt-get install -y kmod cpio binutils cmake binutils-aarch64-linux-gnu git wget pahole automake flex lzop bison gperf build-essential zip curl zlib1g-dev libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip dwarves device-tree-compiler python3 ccache git-lfs gnupg imagemagick libelf-dev libncurses5-dev libsdl1.2-dev gpart fuse2fs e2fsck-static icu-doc rsync adb fastboot libstdc++6 python-is-python3 gcc-aarch64-linux-gnu 
          mkdir -p kernel

      - name: Checkout Kernel Source
        uses: actions/checkout@v6
        with:
          repository: ZYouXPro/android_kernel_oppo_sm7325
          path: kernel/msm-5.4
          fetch-depth: 1
          ref: 5.10-bpf

      - name: Checkout Modules Source
        uses: actions/checkout@v6
        with:
          repository: oppo-source/android_kernel_modules_and_devicetree_oppo_sm7325
          path: temp_modules
          ref: oppo/sm7325_v_15.0.0_k11

      - name: Prepare Compiler
        run: |
          mkdir -p compiler
          cd compiler
          curl -fL "https://github.com/ZYouXPro/android_kernel_oppo_sm7325/releases/download/K11/linux-x86-refs_heads_android12-release-clang-r416183b.tar.gz" -o clang-r416183b.tar.gz --connect-timeout 30 --retry 5 --retry-delay 5
          mkdir -p clang-bin
          tar -xzf clang-r416183b.tar.gz -C clang-bin
          rm clang-r416183b.tar.gz

      - name: Handle Dependencies
        run: |
          mv temp_modules/vendor ./vendor
          mv temp_modules/device ./device
          rm -rf temp_modules

      - name: Set Release Info & Custom Version
        run: |
          BUILD_DATE=$(date +%Y%m%d)
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: Compile Kernel
        run: |
          export PATH="$(pwd)/compiler/clang-bin/bin:$PATH"
          export CROSS_COMPILE="aarch64-linux-android-"
          export CROSS_COMPILE_ARM32="arm-linux-androideabi-"
          export CLANG_TRIPLE="aarch64-linux-gnu-"
          export CLANG_PATH="$(pwd)/compiler/clang-bin/bin"
          export ARCH="arm64"
          export SUBARCH="arm64"
          cd kernel/msm-5.4
          curl -LSs "https://raw.githubusercontent.com/Baka-SU/BakaSU/main/kernel/setup.sh" | bash
          curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/mainline/Patches/syscall_hook_patches.sh" -o syscall_hook_patches.sh
          chmod +x syscall_hook_patches.sh
          bash syscall_hook_patches.sh
          
          # Fuck -dirty
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          echo "KernelSU/" >> .git/info/exclude
          echo "/drivers/kernelsu" >> .git/info/exclude
          git add -A
          git commit -m "apply patches" --no-verify
          
          make O=out CC="clang" LLVM=1 shit_defconfig
          ./scripts/config --file out/.config \
            -e CONFIG_KSU \
            -e CONFIG_KSU_MANUAL_HOOK
          make O=out CC="clang" LLVM=1 -j$(nproc)

      - name: Package with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/ZYouXPro/AnyKernel3.git AnyKernel3
          rm -rf AnyKernel3/.git
          cp kernel/msm-5.4/out/arch/arm64/boot/Image AnyKernel3/
          cd AnyKernel3
          zip -r9 ../BPF-BakaSU-Kernel-${{ env.BUILD_DATE }}.zip . \
            -x ".git*" "README.md" "*placeholder"

      - name: Pack Boot Image
        run: |
          pwd
          mkdir -p boot_pack
          cd boot_pack
          wget https://github.com/ZYouXPro/android_kernel_oppo_sm7325/releases/download/K11/magiskboot
          chmod +x magiskboot
          curl -fL "https://github.com/ZYouXPro/android_kernel_oppo_sm7325/releases/download/K11/boot.img" -o boot_origin.img
          ./magiskboot unpack boot_origin.img
          if [ ! -f "../kernel/msm-5.4/out/arch/arm64/boot/Image" ]; then
            echo "错误：编译出的 Image 文件不存在，请检查编译步骤！"
            exit 1
          fi
          cp ../kernel/msm-5.4/out/arch/arm64/boot/Image kernel
          ./magiskboot repack boot_origin.img ../boot-BPF-BakaSU-${{ env.BUILD_DATE }}.img
          pwd
          cd ..
          pwd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: BakaSU_kernel
          path: |
            BPF-BakaSU-Kernel-${{ env.BUILD_DATE }}.zip
            boot-BPF-BakaSU-${{ env.BUILD_DATE }}.img

      - name: Upload Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.BUILD_DATE }}
          name: KernelSU Kernel for OPLUS SM7325 (${{ env.BUILD_DATE }})
          body: |
            ⌛编译日期: ${{ env.BUILD_DATE }}
            🍼内核版本: 5.4.254
            🍨欢迎刷入ZYOUX的内核！
            🧀ZIP为AnyKernel3可用KSU管理器直接更新哦！
            🥞ColorOS 17及以上版本需要使用BPF版本才能开机！
          files: |
            BPF-BakaSU-Kernel-${{ env.BUILD_DATE }}.zip
            boot-BPF-BakaSU-${{ env.BUILD_DATE }}.img
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

